# Generated by Django 5.1.5 on 2025-02-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
